language: node_js

node_js:
  - node

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build LifeCycle
install:
  - yarn

# before_script:

script:
  # - npm run eslint # 工程测试
  # - npm run dev # 工程测试
  - npm run docs:build # 工程构建打包

git:
  depth: false

branches:
  only:
    - master

# before_deploy:
#   - yarn build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: ./docs/.vuepress/dist/
  skip-cleanup: true
  target-branch: gh-pages
  on:
    branch: master # 当master分支有push事件的时候执行deploy流程